[package]
name = "qoe_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "qoe_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[build-dependencies]
cbindgen = "0.28.0"